language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: pOQ9o9q5oJ0Z65F12esRV91HWovLgJSHjMsPfXO+77CdWTNIhEwjEzFK5L9t1b5djMDLsLrGy/jWZU3TZXcSo+vaDzREcJEjo76mjDLHbnuYpIPkGReTdC51YWqUrHu5+fZoHJsmVg6r+JF3IEH8km4GkWKB3qqeZmuxv4VwTt2sZnHRtyOzlg73xHzD6EE3rp2lVW5+REo9xhQ1q0WUYD4UNyFE+r7L/+ncjrSKIdLumFhqFRxhfvZkka2PLKpjUKXgoYNoU2oWnAU68D0jSo5kEydzgc+J9Zw0VGDEgJYkf/pZYVLdvGm028FMn0BcSFbLDqSxicT2+1jKQqWdT4FX5ooix0k6l27ZNyNhCqn9QQK1R+V5uH4xV2xEv8ugRtOJ4GV2OJEYNtnORfDM3uwj/Xtdlx6Z2xmoM6mdvBlbuTOR+KVbIXk2RNyxJY6TSsqqx4oOYSeTp4AxgpoG7GBdZvaWJQXqgP7YT5PVsmUhEczFV6G88yCDdZY3Z+heAABTKu1uY96RaASpfBKLbOxXaLCGnCjy8//6kWPztCtHMP34Lr1W9BTbSmIVsHkmATVf9TN4CVNCxCafy6ilxk6g7mtW0fXpuVnVJZL+HTvY7vpE3N6VNNsGWRZY4dcZQy6BCT9XmvdKSeDDSNVNZNNPyG5uqi8bCDvUkBuk+JA=
  app: intense-bayou-38216
  on:
    repo: Jollendi91/node-restaurants-app-mongoose
    branch: feature/with-tests
