language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: E5gTiPlMRAh1Qj9fTeaaGVO+LsdH22P18wMIJQhB4GwfvImBDzYJRGg4sWixydbeQ7jcWunA6G9Tsq5+H32tUGxcp4qt6VT4pz4/uiSToNOPYyzZg2ii/KXtqyG2DcKnp2/ZJlrdaEi1TpzoQh7dFSNgRwB7GWK5CtExhbCJx7OQ+aAzRnRaGxt1jvfwWd2Lczh1VjCZsm8Yvb8PPr8O3hiJIVBmeyK5ZrKuNOU6AwP4yHVOd6jLtldrkvpsHDWFRZlUVxUkT02FihOx0Kc784bl3jpDij2Y2b2IRNCFiELU1L7bv3WwCmOPJ0tayGh+E62CWDRdzWosQmcTJ34a4tV7qN9unz83Vz0plTvN2eSZY5l6aN+16IufgVoCYUirakUJYsHuKoH7zYJQuSraHpI2qFjmINXOs1gyilM4ynwm77zrZ3PE2IC+lTOPJhAP+XMv0Z5hkL11t6bZGqxnekOJSyKpng2gsv+41AdFxdDT2V5GFYTA2BCrlgFS8jRWCm8UxyxIKEtx/UDiSdM2xBW5HUApMv1DH43fK5ckik8tVe8kFYmpTZUZxMMgPxHTKFJTAWM/iVBeqWNfPligRRMk/TtmX8pLYiRWb/bEJPwvLpQXWUABCRZEyv/wl1EfhMWgY+6mxApvbgqrc+WSYeiycpE4bKl0VHemW9U/ovI=
  app: intense-bayou-38216
  on:
    repo: Jollendi91/node-restaurants-app-mongoose
    branch: feature/with-tests
