language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: qLCmMwNZSRLaPp6Yk2nCMn5nt4WZY5EYuBq3NwHmINzzHjz6XHy7xbuwoh3IAR6YKDLb3Rf/+67f7M8pqtDU6OlLHz3A/VH74vOLDsp8r3EhMvYi0wXjpAuWXmEssSqceCWoMK+KDKcSN5fect/h1C+xXswWbQycjT3dzU4iDjJFVOupeQ9YokuZHVf//FHXWTSIu2goddydq+a+owJh5uleI3EY82jbeFdT9l/PI6wxozPmmBpU/nBdcN5lFlpTdDG2ypuNidOGq/IU//e6hUlvuv+CUg0ow7z71EHboe36cYFg9O9Znnx/f6797FziD3N5N9kDwzY3M7hlx2FrGQGUD2LawK2sK3HewryyA7JKa6mX9mx5uNw99eApCbiNJNSthgd2TCNUT/ioSRTIpE/kadDpLhS9oJ2sljcrt6uzNLNaXcJBwsC6TRnK/9HP80m2tyQLmnmo8DRPrWRf/86juwsCB7OnKGSLYJomJ0dMyysVxXQ9rXT6tCLSgyt+Qm/jXXPRIxZEnP6j3Th2dsQWs0Rx3JI7wJx8RCo/Bzc/DBhu/jD8C0/nL3iuxDSP06TGFMUT7o2M7oHmio5WoEChZA8/6rx/ANRZK+9iEAADd6D17hhmZWGCqmgfdtW8N1mopKLK+DIIUdVsQ8UBPdmLN7M9qTSvN7w8xSa56/A=
  app: intense-bayou-38216
  on:
    repo: Jollendi91/node-restaurants-app-mongoose
    branch: feature/with-tests
